package com.swapps.cardiopulm.utils

const val HEART_RATE = "HEART_RATE"
const val RESPIRATORY_RATE = "RESPIRATORY_RATE"
const val TIMESTAMP = "TIMESTAMP"
const val INITIATE_HEART_RATE_MEASUREMENT = "INITIATE_HEART_RATE_MEASUREMENT"
const val COUNTDOWN_HEART_RATE_MEASUREMENT = "COUNTDOWN_HEART_RATE_MEASUREMENT"
const val INITIATE_RESPIRATORY_RATE_MEASUREMENT = "INITIATE_RESPIRATORY_RATE_MEASUREMENT"
const val COUNTDOWN_RESPIRATORY_RATE_MEASUREMENT = "COUNTDOWN_RESPIRATORY_RATE_MEASUREMENT"